import test from "node:test";
import assert from "node:assert/strict";
import { careDatabase, asUser } from "./helpers/care-database.mjs";
const family = "10000000-0000-4000-8000-000000000001";
const caregiver = "10000000-0000-4000-8000-000000000002";
const stranger = "10000000-0000-4000-8000-000000000003";
const replacementCaregiver = "10000000-0000-4000-8000-000000000004";
const schedule = { kind: "weekly", startDate: "2090-01-02", endDate: "2090-01-09", days: [0,1,2,3,4,5,6], startTime: "20:00", endTime: "08:00", timezone: "America/Sao_Paulo" };
test("fluxo real: região, assinaturas, plantões, RLS, alterações, chat e encerramento", async () => {
  const db = await careDatabase();
  try {
    await db.query("insert into auth.users(id) values ($1),($2),($3),($4)", [family, caregiver, stranger,replacementCaregiver]);
    await db.query("insert into profiles(id,role,full_name) values ($1,'client','Família'),($2,'caregiver','Cuidador'),($3,'client','Outro'),($4,'caregiver','Substituto')", [family, caregiver, stranger,replacementCaregiver]);
    await db.query("insert into caregiver_profiles(user_id,verification_status) values ($1,'approved'),($2,'approved')", [caregiver,replacementCaregiver]);
    const region = (await db.query("insert into verified_regions(municipality_id,city,state,district,label) values ('3550308','São Paulo','SP','Vila Mariana','Vila Mariana — São Paulo/SP') returning id")).rows[0].id;
    await asUser(db, family);
    const payload = { title: "Acompanhamento noturno", description: "Auxílio durante o período noturno", careType: "Companhia", hourlyRate: 25, regionId: region, schedule };
    await assert.rejects(db.query("select save_care_opportunity(null,$1::jsonb)", [JSON.stringify({ ...payload, regionId: stranger, approximateRegion: "banana" })]), /região/);
    await assert.rejects(db.query("insert into verified_regions(municipality_id,city,state,label) values ('0000000','banana','SP','banana')"), /permission denied/);
    const job = (await db.query("select (save_care_opportunity(null,$1::jsonb)).id", [JSON.stringify(payload)])).rows[0].id;
    assert.equal((await db.query("select approximate_region from opportunities where id=$1", [job])).rows[0].approximate_region, "Vila Mariana — São Paulo/SP");
    await asUser(db, caregiver);
    await db.query("insert into applications(opportunity_id,caregiver_id) values ($1,$2)", [job, caregiver]);
    const chat = (await db.query("select (open_care_conversation($1,null)).id", [job])).rows[0].id;
    await db.query("insert into messages(conversation_id,sender_id,body) values ($1,$2,'Olá')", [chat, caregiver]);
    await asUser(db, family);
    const c = (await db.query("select (propose_contract($1,$2,2400,null,null,$3::jsonb)).id", [job, caregiver, JSON.stringify({ schedule, conditions: "Atendimento conforme a escala acordada." })])).rows[0].id;
    await db.query("select transition_contract($1,'sign')", [c]);
    assert.equal((await db.query("select count(*)::int as n from appointments")).rows[0].n, 0);
    await asUser(db, caregiver);
    await db.query("select transition_contract($1,'sign')", [c]);
    assert.equal((await db.query("select count(*)::int as n from appointments")).rows[0].n, 8);
    await db.query("select transition_contract($1,'sign')", [c]);
    assert.equal((await db.query("select count(*)::int as n from appointments")).rows[0].n, 8, "signature retry does not duplicate shifts");
    await assert.rejects(db.query("select manage_care_appointment(null,$1::jsonb)", [JSON.stringify({ contractId: c, title: "Conflito", startsAt: "2090-01-03T01:00:00Z", endsAt: "2090-01-03T02:00:00Z" })]), /já possui/);
    await assert.rejects(db.query("select manage_care_appointment(null,$1::jsonb)", [JSON.stringify({ contractId: c, title: "Fora do período", startsAt: "2091-01-01T01:00:00Z", endsAt: "2091-01-01T02:00:00Z" })]), /fora do período/);
    await asUser(db, stranger);
    assert.equal((await db.query("select count(*)::int as n from appointments")).rows[0].n, 0);
    await assert.rejects(db.query("select transition_contract($1,'complete')", [c]), /Acesso negado/);
    await asUser(db, family);
    await db.query("insert into contract_care_details(contract_id,address) values ($1,'Endereço privado')", [c]);
    await db.query("select manage_care_task(null,$1::jsonb)", [JSON.stringify({ contractId: c, title: "Hidratação", category: "water", dueAt: "2090-01-03T01:00:00Z", repeatDays: 2 })]);
    await db.query("select change_care_contract($1,$2::jsonb)", [c, JSON.stringify({ action: "propose_change", schedule: { ...schedule, startDate: "2090-01-10", endDate: "2090-01-12" }, grossAmount: 2500, conditions: "Nova escala e valor total revisado." })]);
    const change = (await db.query("select id from contract_changes where contract_id=$1", [c])).rows[0].id;
    await assert.rejects(db.query("select change_care_contract($1,$2::jsonb)", [c, JSON.stringify({ action: "accept_change", changeId: change })]), /outra parte/);
    await asUser(db, caregiver);
    await db.query("select change_care_contract($1,$2::jsonb)", [c, JSON.stringify({ action: "accept_change", changeId: change })]);
    assert.equal((await db.query("select document_version from contracts where id=$1", [c])).rows[0].document_version, 2);
    assert.equal((await db.query("select count(*)::int as n from contract_versions")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int as n from appointments where status='scheduled'")).rows[0].n, 3);
    const sourceAppointment = (await db.query("select id from appointments where contract_id=$1 and status='scheduled' order by starts_at limit 1",[c])).rows[0].id;
    await db.query("select request_care_replacement($1,'Impossibilidade de comparecer neste dia',false)",[sourceAppointment]);
    await asUser(db,family);
    const replacementJob = (await db.query("select request_care_replacement($1,'Contratação para cobrir o plantão solicitado',true) as id",[sourceAppointment])).rows[0].id;
    const replacementSchedule = (await db.query("select schedule from opportunities where id=$1",[replacementJob])).rows[0].schedule;
    await asUser(db,replacementCaregiver);
    await db.query("insert into applications(opportunity_id,caregiver_id) values($1,$2)",[replacementJob,replacementCaregiver]);
    await asUser(db,family);
    const replacementContract = (await db.query("select (propose_contract($1,$2,300,null,null,$3::jsonb)).id",[replacementJob,replacementCaregiver,JSON.stringify({schedule:replacementSchedule,conditions:"Cobertura integral do plantão de substituição."})])).rows[0].id;
    await db.query("select transition_contract($1,'sign')",[replacementContract]);
    assert.equal((await db.query("select status from appointments where id=$1",[sourceAppointment])).rows[0].status,'scheduled','original coverage remains until both signatures');
    await asUser(db,replacementCaregiver);
    await db.query("select transition_contract($1,'sign')",[replacementContract]);
    assert.equal((await db.query("select count(*)::int as n from appointments where contract_id=$1",[replacementContract])).rows[0].n,1);
    await asUser(db,family);
    assert.equal((await db.query("select status from appointments where id=$1",[sourceAppointment])).rows[0].status,'cancelled');
    await asUser(db, family);
    assert.ok(Number((await db.query("select unread from care_chat_summaries()")).rows[0].unread) >= 1);
    const messageId = (await db.query("select id from messages where conversation_id=$1 order by created_at desc,id desc limit 1", [chat])).rows[0].id;
    await db.query("select manage_care_conversation($1,'read',$2)", [chat, messageId]);
    assert.equal(Number((await db.query("select unread from care_chat_summaries()")).rows[0].unread), 0);
    await db.query("select manage_care_conversation($1,'block',null)", [chat]);
    await asUser(db, caregiver);
    await assert.rejects(db.query("insert into messages(conversation_id,sender_id,body,kind) values ($1,$2,'Aceite falso','system')", [chat, caregiver]), /permission denied/);
    await assert.rejects(db.query("insert into messages(conversation_id,sender_id,body) values ($1,$2,'Bloqueada')", [chat, caregiver]), /bloqueada/);
    await db.query("select change_care_contract($1,$2::jsonb)", [c, JSON.stringify({ action: "terminate", reason: "Indisponibilidade para continuar o atendimento." })]);
    assert.equal((await db.query("select count(*)::int as n from appointments where status='scheduled'")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int as n from care_tasks where status='pending'")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int as n from contract_care_details")).rows[0].n, 0, "former caregiver loses access to private address");
  } finally { await db.close(); }
});

test("entrada, saída, avaliações, arquivos privados e lembretes respeitam o ciclo do atendimento", async () => {
  const db = await careDatabase();
  try {
    await db.query("insert into auth.users values ($1),($2),($3)", [family,caregiver,stranger]);
    await db.query("insert into profiles(id,role,full_name) values ($1,'client','Família'),($2,'caregiver','Cuidador'),($3,'client','Outro')",[family,caregiver,stranger]);
    await db.query("insert into caregiver_profiles(user_id,verification_status) values ($1,'approved')",[caregiver]);
    const job = (await db.query("insert into opportunities(client_id,title,description,care_type,approximate_region,hourly_rate,status) values($1,'Cuidado diário','Atendimento de companhia','Companhia','Legado',20,'filled') returning id",[family])).rows[0].id;
    const c = (await db.query("insert into contracts(opportunity_id,client_id,caregiver_id,gross_amount,starts_at,ends_at,status,service_snapshot) values($1,$2,$3,300,now()-interval '1 day',now()+interval '1 day','active','{\"title\":\"Atendimento\"}') returning id",[job,family,caregiver])).rows[0].id;
    const appointment = (await db.query("insert into appointments(contract_id,created_by,title,starts_at,ends_at) values($1,$2,'Plantão',now()-interval '1 minute',now()+interval '30 minutes') returning id",[c,family])).rows[0].id;
    await db.query("insert into contract_care_details(contract_id,address,consented_by) values($1,'Rua privada',$2)",[c,family]);
    await db.query("insert into care_files(contract_id,uploaded_by,name,path,mime_type,size_bytes) values($1,$2,'Plano.pdf','private/path','application/pdf',100)",[c,family]);
    await db.query("insert into push_subscriptions(endpoint,user_id,keys) values('https://fcm.googleapis.com/fcm/send/test',$1,'{}')",[caregiver]);
    await asUser(db,stranger);
    assert.equal((await db.query("select * from care_files")).rows.length,0);
    assert.equal((await db.query("select * from contract_care_details")).rows.length,0);
    await assert.rejects(db.query("select claim_care_push()"),/permission denied/);
    await asUser(db,family);
    await assert.rejects(db.query("select submit_care_review($1,5,'Excelente')",[c]),/Conclua/);
    await assert.rejects(db.query("select manage_care_appointment($1,'{\"action\":\"checkin\"}')",[appointment]),/indisponível/);
    await asUser(db,caregiver);
    assert.equal((await db.query("select * from care_files")).rows.length,1);
    await db.query("select manage_care_appointment($1,'{\"action\":\"checkin\"}')",[appointment]);
    await assert.rejects(db.query("select manage_care_appointment($1,'{\"action\":\"checkin\"}')",[appointment]),/indisponível/);
    await asUser(db,family);
    await assert.rejects(db.query("select transition_contract($1,'complete')",[c]),/plantão/);
    await asUser(db,caregiver);
    await db.query("select manage_care_appointment($1,'{\"action\":\"checkout\"}')",[appointment]);
    assert.equal((await db.query("select status from appointments where id=$1",[appointment])).rows[0].status,'completed');
    await db.exec("reset role");
    await db.query("insert into care_tasks(contract_id,title,category,due_at,assigned_to) values($1,'Água','water',now()+interval '2 minutes',$2)",[c,caregiver]);
    await db.exec("select enqueue_care_reminders(); select enqueue_care_reminders();");
    assert.equal((await db.query("select count(*)::int as n from care_reminder_keys")).rows[0].n,1);
    const claim = await db.query("select * from claim_care_push()");
    assert.ok(claim.rows.length>0);
    assert.equal((await db.query("select * from claim_care_push()")).rows.length,0,"leased jobs are not claimed twice");
    await asUser(db,family);
    await db.query("select transition_contract($1,'complete')",[c]);
    await db.query("select submit_care_review($1,5,'Ótima comunicação')",[c]);
    await assert.rejects(db.query("select submit_care_review($1,5,'Duplicada')",[c]),/duplicate key/);
    // The caregiver can always inspect their own professional summary.
    await asUser(db,caregiver);
    assert.equal(Number((await db.query("select care_applicant_profile($1) as profile",[caregiver])).rows[0].profile.rating),5);
    assert.equal((await db.query("select * from care_files")).rows.length,0);
    assert.equal((await db.query("select * from contract_care_details")).rows.length,0);
    await db.query("select submit_care_review($1,4,'Bom atendimento da família')",[c]);
    assert.equal((await db.query("select count(*)::int as n from care_reviews")).rows[0].n,2);
  } finally { await db.close(); }
});
