"use client";
import { useCallback, useEffect, useRef, useState } from "react";
type Appointment = { id: string; contract_id: string; title: string; description: string | null; starts_at: string; ends_at: string; status: string; checked_in_at: string | null; checked_out_at: string | null; reason: string | null; replacement_requested_at: string | null; replacement_reason: string | null; contracts: { caregiver_id: string; service_snapshot: { title: string; schedule: { timezone?: string } } } };
type Contract = { id: string; status: string; opportunities: { title: string } | null };
const statusLabels: Record<string, string> = { scheduled: "Agendado", completed: "Realizado", cancelled: "Cancelado", missed: "Falta" };
function localInput(value: string) { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export function AgendaView() {
  const [items, setItems] = useState<Appointment[]>([]); const [contracts, setContracts] = useState<Contract[]>([]); const [userId, setUserId] = useState("");
  const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [filter, setFilter] = useState(""); const [date, setDate] = useState(""); const [status, setStatus] = useState("scheduled");
  const [editor, setEditor] = useState<Appointment | "new" | null>(null);
  const load = useCallback(async () => { const responses = await Promise.all([fetch("/api/appointments", { cache: "no-store" }), fetch("/api/contracts", { cache: "no-store" })]); const [appointmentsBody, contractsBody] = await Promise.all(responses.map(response => response.json())); if (!responses[0].ok || !responses[1].ok) throw new Error(appointmentsBody.error ?? contractsBody.error); setItems(appointmentsBody.appointments); setUserId(appointmentsBody.currentUserId); setContracts(contractsBody.contracts.filter((c: Contract) => c.status === "active")); }, []);
  useEffect(() => { void Promise.resolve().then(load).catch(cause => setError(cause.message)).finally(() => setLoading(false)); }, [load]);
  async function mutate(payload: object, method = "PATCH") { setBusy(true); setError(""); try { const response = await fetch("/api/appointments", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setEditor(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao atualizar agenda."); } finally { setBusy(false); } }
  const visible = items.filter(item => (!filter || item.contract_id === filter) && (!status || item.status === status) && (!date || new Intl.DateTimeFormat("en-CA", { timeZone: item.contracts.service_snapshot?.schedule?.timezone ?? "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(item.starts_at)) === date));
  const allContracts = [...new Map(items.map(item => [item.contract_id, item.contracts.service_snapshot?.title ?? item.title])).entries()];
  return <section className="agenda-page"><div className="section-heading"><div><h2 className="panel-title">Agenda de atendimento</h2><p className="subtle">Plantões gerados a partir dos contratos, com registro de entrada e saída.</p></div><button className="primary" disabled={!contracts.length} onClick={() => setEditor("new")}>Novo compromisso</button></div>
    <div className="opportunity-form"><label>Contrato<select value={filter} onChange={e => setFilter(e.target.value)}><option value="">Todos</option>{allContracts.map(([id, title]) => <option key={id} value={id}>{title}</option>)}</select></label><label>Data<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label>Situação<select value={status} onChange={e => setStatus(e.target.value)}><option value="">Todas</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    {error && !editor && <p role="alert">{error}</p>}{loading && <p>Carregando agenda...</p>}{!loading && !visible.length && <p>Nenhum compromisso neste filtro.</p>}
    <section className="panel agenda-list">{visible.map(item => { const zone = item.contracts.service_snapshot?.schedule?.timezone ?? "America/Sao_Paulo"; const format = (value: string) => new Date(value).toLocaleString("pt-BR", { timeZone: zone }); const active = contracts.some(c => c.id === item.contract_id); return <article className="agenda-item" key={item.id}><div><strong>{item.title}</strong><p>{format(item.starts_at)} — {format(item.ends_at)} · {zone}</p><p>{statusLabels[item.status]} · {item.description}</p>{item.reason && <p>Motivo: {item.reason}</p>}{item.replacement_requested_at && <p>Substituição solicitada: {item.replacement_reason}. O plantão permanece agendado até o aceite de outro contrato.</p>}{item.checked_in_at && <p>Entrada: {format(item.checked_in_at)}{item.checked_out_at && ` · Saída: ${format(item.checked_out_at)}`}</p>}
      {active && item.status === "scheduled" && <div className="contract-actions">{!item.checked_in_at && <><button disabled={busy} className="filter" onClick={() => { const reason = window.prompt("Motivo da substituição (mínimo 10 caracteres):"); if (reason) void mutate({ id: item.id, action: "replacement", reason, publish: userId !== item.contracts.caregiver_id }); }}>{userId === item.contracts.caregiver_id ? "Solicitar substituição" : "Publicar vaga de substituição"}</button><button disabled={busy} className="filter" onClick={() => { setError(""); setEditor(item); }}>Reagendar</button>{["cancel", "missed"].map(action => <button key={action} disabled={busy} className="filter" onClick={() => { const reason = window.prompt(action === "cancel" ? "Motivo do cancelamento:" : "Motivo da falta:"); if (reason) void mutate({ id: item.id, action, reason }); }}>{action === "cancel" ? "Cancelar" : "Registrar falta"}</button>)}</>}{userId === item.contracts.caregiver_id && <button disabled={busy} className="primary" onClick={() => void mutate({ id: item.id, action: item.checked_in_at ? "checkout" : "checkin" })}>{item.checked_in_at ? "Registrar saída" : "Registrar entrada"}</button>}</div>}
    </div></article>; })}</section>
    {editor && <AppointmentEditor item={editor} contracts={contracts} error={error} busy={busy} onClose={() => setEditor(null)} onSave={mutate} />}
  </section>;
}
function AppointmentEditor({ item, contracts, error, busy, onClose, onSave }: { item: Appointment | "new"; contracts: Contract[]; error: string; busy: boolean; onClose: () => void; onSave: (payload: object, method?: string) => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null); const editing = item !== "new";
  useEffect(() => { const element = dialog.current; element?.showModal(); return () => element?.close(); }, []);
  return <dialog ref={dialog} className="contract-dialog" aria-labelledby="appointment-title" onCancel={event => { event.preventDefault(); if (!busy) onClose(); }}><header className="contract-dialog-header"><h2 id="appointment-title">{editing ? "Reagendar compromisso" : "Novo compromisso"}</h2><button className="filter" disabled={busy} onClick={onClose}>Fechar</button></header><div className="contract-dialog-content"><p>Informe os horários no fuso deste dispositivo. O sistema confere conflitos com outros atendimentos e o período contratado.</p><form className="opportunity-form" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); const times = { startsAt: new Date(String(f.get("start"))).toISOString(), endsAt: new Date(String(f.get("end"))).toISOString() }; void onSave(editing ? { id: item.id, action: "reschedule", reason: f.get("reason"), ...times } : { contractId: f.get("contract"), title: f.get("title"), description: f.get("description"), ...times }, editing ? "PATCH" : "POST"); }}>
    {!editing && <><label>Contrato<select name="contract">{contracts.map(c => <option key={c.id} value={c.id}>{c.opportunities?.title}</option>)}</select></label><label>Título<input name="title" minLength={3} maxLength={160} required /></label><label>Observações<textarea name="description" maxLength={3000} /></label></>}
    <label>Início<input name="start" type="datetime-local" defaultValue={editing ? localInput(item.starts_at) : ""} required /></label><label>Término<input name="end" type="datetime-local" defaultValue={editing ? localInput(item.ends_at) : ""} required /></label>{editing && <label>Motivo<textarea name="reason" minLength={3} maxLength={3000} required /></label>}{error && <p role="alert">{error}</p>}<button className="primary" disabled={busy}>Salvar</button>
  </form></div></dialog>;
}
