"use client";
import { CareFiles } from "@/app/care-files";
import { useCallback, useEffect, useState } from "react";
import { emptySchedule, ScheduleFields } from "@/app/planning-fields";
import { CareSchedule, scheduleSchema, scheduleSummary } from "@/lib/care-planning";

type Task = { id: string; title: string; due_at: string; status: string; notes: string; assigned_to: string; recorded_at: string | null };
type Change = { id: string; proposed_by: string; schedule: CareSchedule; gross_amount: number; conditions: string; status: string };
type Review = { id: string; author_id: string; rating: number; comment: string };
type CareData = { currentUserId: string; details: { address: string; care_notes: string; emergency_contact: string } | null; tasks: Task[]; hasMoreTasks: boolean; changes: Change[]; reviews: Review[]; versions: { version: number }[] };
export function ContractCare({ contractId, role, status, schedule: initialSchedule, amount, onChanged }: { contractId: string; role: "client" | "caregiver"; status: string; schedule: unknown; amount: number; onChanged: () => Promise<void> }) {
  const [data, setData] = useState<CareData | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const [taskPage, setTaskPage] = useState(0); const [taskStatus, setTaskStatus] = useState("pending");
  const [schedule, setSchedule] = useState(() => { const parsed = scheduleSchema.safeParse(initialSchedule); return parsed.success ? parsed.data : emptySchedule; });
  const load = useCallback(async () => { const response = await fetch(`/api/contracts/${contractId}/care?page=${taskPage}&taskStatus=${taskStatus}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }, [contractId, taskPage, taskStatus]);
  useEffect(() => { void Promise.resolve().then(load).catch(cause => setError(cause.message)); }, [load]);
  async function save(payload: object, contract = false) {
    setBusy(true); setError(""); setNotice("");
    try { const response = await fetch(`/api/contracts/${contractId}${contract ? "" : "/care"}`, { method: contract ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); if (contract) await onChanged(); setNotice("Alteração salva."); return true; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar."); return false; } finally { setBusy(false); }
  }
  const editable = ["active", "pending_signatures"].includes(status);
  const pending = data?.changes.find(change => change.status === "pending");
  return <><section><h3>Documento e alterações</h3><a className="link" href={`/api/contracts/${contractId}/document`}>Baixar contrato e registros de aceite</a>{data?.versions.map(version => <p key={version.version}><a href={`/api/contracts/${contractId}/document?version=${version.version}`}>Baixar versão {version.version}</a></p>)}
    {error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    {pending && <article className="medication-item"><h4>Alteração aguardando resposta</h4><p>{scheduleSummary(pending.schedule)}</p><p>Valor total revisado do contrato: R$ {Number(pending.gross_amount).toFixed(2)}</p><p>{pending.conditions}</p>{pending.proposed_by === data?.currentUserId ? <button disabled={busy} className="filter" onClick={() => void save({ action: "withdraw_change", changeId: pending.id }, true)}>Retirar proposta</button> : <><button disabled={busy} className="primary" onClick={() => void save({ action: "accept_change", changeId: pending.id }, true)}>Aceitar alteração</button><button disabled={busy} className="filter" onClick={() => void save({ action: "reject_change", changeId: pending.id }, true)}>Recusar</button></>}</article>}
    {editable && !pending && <details><summary>Propor alteração / contraproposta</summary><p>Ao aceitar uma alteração de contrato ativo, ambas as partes concordam com a nova versão. A escala abaixo substitui os plantões futuros; atendimentos realizados permanecem no histórico. O valor informado é o total revisado do contrato, incluindo o que já foi realizado.</p><form className="opportunity-form" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void save({ action: "propose_change", schedule, grossAmount: Number(f.get("amount")), conditions: f.get("conditions") }, true); }}><ScheduleFields value={schedule} onChange={setSchedule} /><label>Valor total revisado (R$)<input name="amount" type="number" min="0.01" max="1000000" step="0.01" defaultValue={amount} required /></label><label className="opportunity-form-full">Condições e motivo da alteração<textarea name="conditions" required minLength={10} maxLength={5000} /></label><button className="primary" disabled={busy}>Propor alteração</button></form></details>}
    {status === "active" && <details><summary>Encerrar antecipadamente</summary><p>Os plantões futuros serão cancelados e a outra parte será avisada. Acertos financeiros devem seguir as condições acordadas.</p><form onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); if (window.confirm("Encerrar este contrato e cancelar os plantões pendentes?")) void save({ action: "terminate", reason: f.get("reason") }, true); }}><label>Motivo<textarea name="reason" minLength={10} maxLength={3000} required /></label><button className="filter" disabled={busy}>Confirmar encerramento</button></form></details>}
  </section>
  <section><h3>Informações privadas do atendimento</h3><p className="subtle">Endereço, orientações e contato de emergência ficam disponíveis ao cuidador durante o contrato ativo.</p>
    {role === "client" && editable && data ? <form key={data.details?.address ?? "empty"} className="opportunity-form" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void save({ action: "details", address: f.get("address"), careNotes: f.get("careNotes"), emergencyContact: f.get("emergencyContact"), consent: f.get("consent") === "on" }); }}><label className="opportunity-form-full">Endereço completo<textarea name="address" maxLength={1000} defaultValue={data.details?.address} /></label><label className="opportunity-form-full">Orientações necessárias ao atendimento<textarea name="careNotes" maxLength={5000} defaultValue={data.details?.care_notes} /></label><label>Contato de emergência<input name="emergencyContact" maxLength={500} defaultValue={data.details?.emergency_contact} /></label><label><input type="checkbox" name="consent" required />Tenho autorização para compartilhar estas informações com o cuidador contratado.</label><button className="primary" disabled={busy}>Salvar informações privadas</button></form> : <><p className="contract-text">{data?.details?.address || "Endereço ainda não disponível."}</p><p className="contract-text">{data?.details?.care_notes}</p><p>{data?.details?.emergency_contact}</p></>}
  </section>
  <CareFiles contractId={contractId} canUpload={status === "active" || (role === "client" && status === "pending_signatures")} /><section><h3>Rotina de cuidado</h3>{role === "client" && status === "active" && <details><summary>Adicionar tarefa à rotina</summary><form className="opportunity-form" onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); if (await save({ action: "task", title: f.get("title"), category: f.get("category"), dueAt: new Date(String(f.get("dueAt"))).toISOString(), repeatDays: Number(f.get("repeatDays")) })) form.reset(); }}><label>Tarefa<input name="title" minLength={3} maxLength={160} required /></label><label>Categoria<select name="category"><option value="food">Alimentação</option><option value="water">Hidratação</option><option value="hygiene">Higiene</option><option value="mobility">Mobilidade</option><option value="other">Outra</option></select></label><label>Primeiro horário (fuso deste dispositivo)<input name="dueAt" type="datetime-local" required /></label><label>Repetir diariamente por quantos dias?<input name="repeatDays" type="number" min={1} max={90} defaultValue={1} required /></label><button className="primary" disabled={busy}>Criar tarefas</button></form></details>}
    <div className="opportunity-form"><label>Mostrar tarefas<select value={taskStatus} onChange={event => { setTaskStatus(event.target.value); setTaskPage(0); }}><option value="pending">Pendentes</option><option value="all">Todas</option><option value="done">Realizadas</option><option value="skipped">Não realizadas</option><option value="cancelled">Canceladas</option></select></label></div>{data?.tasks.length === 0 && <p>Nenhuma tarefa cadastrada.</p>}{data?.tasks.map(task => <article className="medication-item" key={task.id}><h4>{task.title}</h4><p>{new Date(task.due_at).toLocaleString("pt-BR")} · {{ pending: "Pendente", done: "Realizada", skipped: "Não realizada", cancelled: "Cancelada" }[task.status]}</p><p>{task.notes}</p>{task.recorded_at && <small>Registrada em {new Date(task.recorded_at).toLocaleString("pt-BR")}</small>}{status === "active" && task.status === "pending" && <form onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void save({ action: "record", taskId: task.id, status: f.get("status"), notes: f.get("notes") }); }}><label>Resultado<select name="status">{role === "caregiver" ? <><option value="done">Realizada</option><option value="skipped">Não realizada</option></> : <option value="cancelled">Cancelar tarefa</option>}</select></label><label>Observações / justificativa<textarea name="notes" maxLength={3000} /></label><button className="filter" disabled={busy}>Registrar</button></form>}</article>)}<div className="contract-actions"><button className="filter" disabled={busy || taskPage === 0} onClick={() => setTaskPage(page => page - 1)}>Anterior</button><span>Página {taskPage + 1}</span><button className="filter" disabled={busy || !data?.hasMoreTasks} onClick={() => setTaskPage(page => page + 1)}>Próxima</button></div>
  </section>
  {status === "completed" && <section><h3>Avaliação do atendimento</h3>{data?.reviews.map(review => <article key={review.id}><strong>{review.rating}/5</strong><p>{review.comment}</p></article>)}{data && !data.reviews.some(review => review.author_id === data.currentUserId) && <form onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void save({ action: "review", rating: Number(f.get("rating")), comment: f.get("comment") }); }}><label>Nota<select name="rating">{[5, 4, 3, 2, 1].map(value => <option key={value}>{value}</option>)}</select></label><label>Comentário (sem informações pessoais ou de saúde)<textarea name="comment" maxLength={2000} /></label><button className="primary" disabled={busy}>Enviar avaliação</button></form>}</section>}</>;
}
