"use client";

import { Bell, ClipboardList, FileText, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";

type Role = "client" | "caregiver";
type Counts = { opportunities: number; applications: number; contracts: number; unread: number };

export function DashboardView({ role, onNavigate }: { role: Role; onNavigate?: (view: string) => void }) {
  const [counts, setCounts] = useState<Counts | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/opportunities"), fetch("/api/applications"), fetch("/api/contracts"), fetch("/api/notifications")]).then(async ([opportunities, applications, contracts, notifications]) => { const bodies = await Promise.all([opportunities.json(), applications.json(), contracts.json(), notifications.json()]); if (!opportunities.ok || !applications.ok || !contracts.ok || !notifications.ok) throw new Error("Não foi possível carregar o resumo."); setCounts({ opportunities: bodies[0].opportunities.length, applications: bodies[1].applications.length, contracts: bodies[2].contracts.filter((item: { status: string }) => item.status === "active").length, unread: bodies[3].notifications.filter((item: { read_at: string | null }) => !item.read_at).length }); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Não foi possível carregar o resumo.")); }, []);
  const cards = counts ? [{ icon: <Sparkles size={18} />, tone: "green", label: role === "client" ? "Oportunidades publicadas" : "Oportunidades disponíveis", value: counts.opportunities }, { icon: <ClipboardList size={18} />, tone: "blue", label: role === "client" ? "Candidaturas recebidas" : "Minhas candidaturas", value: counts.applications }, { icon: <FileText size={18} />, tone: "green", label: "Contratos ativos", value: counts.contracts }, { icon: <Bell size={18} />, tone: "peach", label: "Notificações não lidas", value: counts.unread }] : [];
  const steps = role === "client" ? [["Publicar oportunidade", "1. Descreva o cuidado necessário"], ["Candidaturas recebidas", "2. Conheça os candidatos"], ["Meus contratos", "3. Combine e assine o contrato"]] : [["Encontrar oportunidades", "1. Encontre vagas na sua região"], ["Minhas candidaturas", "2. Acompanhe suas candidaturas"], ["Meus contratos", "3. Confira propostas e contratos"]];
  return <><section className="panel dashboard-guide"><h2>{role === "client" ? "Como encontrar cuidado" : "Organize seu trabalho"}</h2><p>{role === "client" ? "Publique a necessidade, converse com os candidatos e confira valores e horários antes de assinar." : "Confira região, tarefas, horários e valor de cada vaga. A assinatura das duas partes gera os plantões na agenda."}</p><div className="contract-actions">{steps.map(([view,label])=><button className="filter" key={view} onClick={()=>onNavigate?.(view)}>{label}</button>)}</div><div className="contract-actions"><button className="primary" onClick={()=>onNavigate?.("Agenda")}>{role === "client" ? "Ver meus próximos atendimentos" : "Ver meus próximos plantões"}</button><button className="filter" onClick={()=>onNavigate?.("Mensagens")}>Abrir conversas</button></div></section>{error && <p role="alert" className="agenda-empty">{error}</p>}<section className="stats" aria-label="Resumo da conta">{cards.map((card) => <div className="stat" key={card.label}><div><p>{card.label}</p><strong>{String(card.value).padStart(2, "0")}</strong></div><span className={`stat-icon ${card.tone}`}>{card.icon}</span></div>)}</section></>;
}
