"use client";

import { Plus } from "lucide-react";
import { useEffect, useState } from "react";

type Entry = { id: string; contract_id: string; body: string; created_at: string };
type Contract = { id: string; opportunities?: { title?: string } | null };

export function DiaryViewReal() {
  const [allContracts, setAllContracts] = useState<Contract[]>([]);
  const [filter, setFilter] = useState("");
  const [entries, setEntries] = useState<Entry[]>([]); const [contracts, setContracts] = useState<Contract[]>([]); const [contractId, setContractId] = useState(""); const [body, setBody] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([fetch("/api/diary"), fetch("/api/contracts")]).then(async ([diary, contractsResponse]) => { const diaryBody = await diary.json(); const contractsBody = await contractsResponse.json(); if (!diary.ok || !contractsResponse.ok) throw new Error(diaryBody.error ?? contractsBody.error); const active = (contractsBody.contracts ?? []).filter((item: { status: string }) => item.status === "active"); setEntries(diaryBody.entries ?? []); setAllContracts(contractsBody.contracts ?? []); setContracts(active); setContractId(active[0]?.id ?? ""); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Não foi possível carregar o diário.")); }, []);
  const add = async () => { if (!body.trim() || !contractId) return; setSaving(true); setError(""); try { const response = await fetch("/api/diary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contractId, body }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setEntries((current) => [result.entry, ...current]); setBody(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível registrar a anotação."); } finally { setSaving(false); } };
  return <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Diário de bordo</h2><p className="subtle">Registros persistidos e visíveis apenas às partes do contrato.</p></div></div>{contracts.length > 0 && <div className="opportunity-form"><label>Contrato<select value={contractId} onChange={(event) => setContractId(event.target.value)}>{contracts.map((contract) => <option key={contract.id} value={contract.id}>{contract.opportunities?.title ?? "Contrato ativo"}</option>)}</select></label><label className="opportunity-form-full">Nova anotação<textarea value={body} onChange={(event) => setBody(event.target.value)} maxLength={3000} /></label><button className="primary" disabled={saving || !body.trim()} onClick={() => void add()}><Plus size={16} /> {saving ? "Salvando..." : "Registrar"}</button></div>}{error && <p role="alert" className="agenda-empty">{error}</p>}{!error && !contracts.length && <p className="agenda-empty">É necessário um contrato ativo para registrar o diário.</p>}<label>Filtrar por contrato<select value={filter} onChange={event => setFilter(event.target.value)}><option value="">Todos</option>{allContracts.map(contract => <option key={contract.id} value={contract.id}>{contract.opportunities?.title ?? contract.id}</option>)}</select></label><div className="mini-list">{entries.filter(entry => !filter || entry.contract_id === filter).map((entry) => <div className="mini-row" key={entry.id}><div><strong>{allContracts.find(contract => contract.id === entry.contract_id)?.opportunities?.title ?? entry.contract_id}</strong><p>{entry.body}</p><small>{new Date(entry.created_at).toLocaleString("pt-BR")}</small></div></div>)}</div></section>;
}
