"use client";
import { useRef, useState } from "react";
import { CareSchedule, states, timezones, weekdays } from "@/lib/care-planning";
export type Region = { id: string; label: string; city: string; state: string; municipality_id: string; district: string };
export function LocationField({ value, onChange }: { value: Region | null; onChange: (region: Region | null) => void }) {
  const [state, setState] = useState(""); const [cities, setCities] = useState<{ id: string; name: string }[]>([]);
  const [cep, setCep] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const version = useRef(0);
  async function resolve(payload: object) {
    const attempt = ++version.current; onChange(null); setBusy(true); setError("");
    try { const response = await fetch("/api/locations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (attempt === version.current) onChange(body.region); }
    catch (cause) { if (attempt === version.current) setError(cause instanceof Error ? cause.message : "Falha na consulta."); } finally { if (attempt === version.current) setBusy(false); }
  }
  return <fieldset className="opportunity-form-full planning-fields"><legend>Localização aproximada</legend><p className="subtle">Selecione um município ou consulte o CEP para incluir o bairro. O CEP e a rua não aparecem na vaga.</p><div className="opportunity-form"><label>UF<select value={state} onChange={async event => { const next = event.target.value; setState(next); setCities([]); onChange(null); setError(""); const attempt = ++version.current; setBusy(false); if (!next) return; setBusy(true); try { const response = await fetch(`/api/locations?state=${next}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (attempt === version.current) setCities(body.municipalities); } catch (cause) { if (attempt === version.current) setError(cause instanceof Error ? cause.message : "Consulta indisponível."); } finally { if (attempt === version.current) setBusy(false); } }}><option value="">Selecione</option>{states.map(uf => <option key={uf}>{uf}</option>)}</select></label><label>Município<select disabled={!cities.length || busy} value={value?.municipality_id ?? ""} onChange={event => { if (event.target.value) void resolve({ municipalityId: event.target.value }); else { ++version.current; onChange(null); } }}><option value="">Selecione</option>{cities.map(city => <option key={city.id} value={city.id}>{city.name}</option>)}</select></label><label>CEP (opcional)<input inputMode="numeric" maxLength={9} value={cep} onChange={event => { setCep(event.target.value.replace(/\D/g, "").slice(0, 8)); ++version.current; setBusy(false); onChange(null); }} /></label><button className="filter" type="button" disabled={busy || cep.length !== 8} onClick={() => void resolve({ cep })}>Consultar CEP</button></div>{busy && <p role="status">Validando localização...</p>}{value && <p role="status">Região selecionada: <strong>{value.label}</strong></p>}{error && <p role="alert">{error}</p>}</fieldset>;
}
export const emptySchedule: CareSchedule = { kind: "weekly", startDate: "", endDate: "", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "17:00", timezone: "America/Sao_Paulo" };
export function ScheduleFields({ value, onChange }: { value: CareSchedule; onChange: (value: CareSchedule) => void }) {
  return <fieldset className="opportunity-form-full planning-fields"><legend>Escala de atendimento</legend><div className="opportunity-form"><label>Frequência<select value={value.kind} onChange={e => onChange({ ...value, kind: e.target.value as CareSchedule["kind"], endDate: e.target.value === "once" ? value.startDate : value.endDate })}><option value="weekly">Semanal</option><option value="once">Pontual</option></select></label><label>Fuso do atendimento<select value={value.timezone} onChange={e => onChange({ ...value, timezone: e.target.value as CareSchedule["timezone"] })}>{timezones.map(zone => <option key={zone}>{zone}</option>)}</select></label><label>Primeira data<input required type="date" value={value.startDate} onChange={e => onChange({ ...value, startDate: e.target.value, endDate: value.kind === "once" ? e.target.value : value.endDate })} /></label>{value.kind === "weekly" && <label>Última data<input required type="date" min={value.startDate} value={value.endDate} onChange={e => onChange({ ...value, endDate: e.target.value })} /></label>}<label>Início do turno<input required type="time" value={value.startTime} onChange={e => onChange({ ...value, startTime: e.target.value })} /></label><label>Fim do turno<input required type="time" value={value.endTime} onChange={e => onChange({ ...value, endTime: e.target.value })} /></label></div>{value.kind === "weekly" && <div className="weekday-options">{weekdays.map((name, day) => <label key={day}><input type="checkbox" checked={value.days.includes(day)} onChange={e => onChange({ ...value, days: e.target.checked ? [...value.days, day].sort() : value.days.filter(item => item !== day) })} />{name}</label>)}</div>}<p className="subtle">Término anterior ao início indica um plantão que termina no dia seguinte. Período máximo: 366 dias.</p></fieldset>;
}
