"use client";
import { useEffect, useState } from "react";
type RequestItem = { id: string; user_id?: string; request_type: string; status: string; details: string; response_note: string | null; created_at: string };
const kinds: Record<string,string> = { export: "Exportação", correction: "Correção", deletion: "Exclusão / encerramento", consent_revocation: "Revogação de consentimento" };
const statuses: Record<string,string> = { requested: "Recebido", in_progress: "Em análise", completed: "Concluído", rejected: "Não atendido — consulte a resposta" };

export function PrivacySettings({ admin = false }: { admin?: boolean }) {
  const [items,setItems] = useState<RequestItem[]>([]); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  const endpoint = admin ? "/api/admin/privacy-requests" : "/api/privacy/requests";
  async function load() { const response=await fetch(endpoint,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setItems(body.requests); }
  useEffect(()=>{let live=true;void fetch(endpoint,{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(live)setItems(body.requests);}).catch(cause=>{if(live)setError(cause.message);});return()=>{live=false;};},[endpoint]);
  async function send(payload: Record<string,unknown>) {setBusy(true);setError("");try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();return true;}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao salvar.");return false;}finally{setBusy(false);}}
  return <section className={admin ? "panel privacy-panel" : "privacy-settings"}>{admin && <h3>Solicitações de privacidade</h3>}{error&&<p role="alert">{error}</p>}
    {!admin&&<><div className="privacy-heading"><div><h3>Privacidade e seus dados</h3><p>Exporte seus dados ou envie um pedido à equipe.</p></div><a className="link" href="/api/privacy/export">Baixar meus dados</a></div><details className="privacy-policy"><summary>O que acontece ao encerrar a conta?</summary><p>Pedidos de exclusão passam por análise. Encerrar a conta remove o acesso, foto, documentos cadastrais e mensagens de texto enviadas. Contratos, registros de atendimento, auditoria e registros financeiros compartilhados podem permanecer; a administração deve explicar o que será preservado e por quê.</p></details><form className="privacy-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const f=new FormData(form);if(await send({requestType:f.get("type"),details:f.get("details")})){form.reset();form.dispatchEvent(new Event('zelou:saved',{bubbles:true}));}}}><label>Tipo de solicitação<select name="type"><option value="correction">Corrigir meus dados</option><option value="deletion">Encerrar minha conta</option><option value="consent_revocation">Rever meus consentimentos</option></select></label><label className="privacy-details-label">Detalhes <span>(opcional)</span><textarea name="details" maxLength={2000} placeholder="Como podemos ajudar?" /></label><button className="primary" disabled={busy}>{busy ? "Enviando..." : "Enviar solicitação"}</button></form></>}
    {items.map(item=><article className="stripe-test-record" key={item.id}><strong>{kinds[item.request_type]} · {statuses[item.status]}</strong><p>{new Date(item.created_at).toLocaleString("pt-BR")}</p><p>{item.details}</p>{item.response_note&&<p>Resposta: {item.response_note}</p>}{admin&&!["completed","rejected"].includes(item.status)&&<form onSubmit={async event=>{event.preventDefault();const f=new FormData(event.currentTarget);const action=f.get("action");if(action==='close_account'&&!window.confirm(`Encerrar a conta ${item.user_id}? Esta operação remove o acesso e dados cadastrais; o histórico compartilhado será preservado.`))return;await send({id:item.id,action,note:f.get("note"),confirmUserId:item.user_id,retentionReviewed:f.get("retention")==='on'});}}><p>Conta: <code>{item.user_id}</code></p><label>Ação<select name="action"><option value="in_progress">Iniciar / atualizar análise</option><option value="rejected">Não atender e justificar</option>{item.request_type==='deletion'?<option value="close_account">Encerrar conta / retomar processamento</option>:<option value="completed">Concluir após atender</option>}</select></label><label>Resposta e justificativa dos registros preservados<textarea name="note" minLength={10} maxLength={3000} required defaultValue={item.response_note??''}/></label>{item.request_type==='deletion'&&<label><input type="checkbox" name="retention"/>Revisei contratos, registros de atendimento e financeiros, inclusive na Stripe; registrei a justificativa de retenção e comuniquei o resultado ao solicitante antes do encerramento.</label>}<button className="primary" disabled={busy}>Aplicar ação</button></form>}</article>)}{!items.length&&<p>Nenhuma solicitação registrada.</p>}
  </section>;
}
