"use client";
import { useEffect, useState } from "react";
import { weekdays } from "@/lib/care-planning";
type Professional = { name: string; city: string; state: string; bio: string; experienceYears: number; specialties: string[]; hourlyRate: number; availability: { days?: number[]; notes?: string }; rating: number | null; reviewCount: number; verificationStatus: string; completedContracts: number };
export function ProfessionalProfile({ caregiverId, editable = false }: { caregiverId?: string; editable?: boolean }) {
  const [profile, setProfile] = useState<Professional | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { let live = true; void fetch(`/api/professional${caregiverId ? `?caregiverId=${caregiverId}` : ""}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); if (live) setProfile(body.professional); }).catch(cause => { if (live) setError(cause.message); }); return () => { live = false; }; }, [caregiverId]);
  return <section className="professional-profile"><h3>{editable ? "Meu perfil profissional" : profile?.name ?? "Perfil profissional"}</h3>{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{profile && (editable ? <form className="opportunity-form" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(""); const f = new FormData(event.currentTarget); try { const response = await fetch("/api/professional", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bio: f.get("bio"), experienceYears: Number(f.get("years")), specialties: String(f.get("specialties")).split(",").map(s => s.trim()).filter(Boolean), hourlyRate: Number(f.get("rate")), availability: { days: f.getAll("day").map(Number), notes: f.get("notes") } }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setNotice("Perfil profissional salvo."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao salvar."); } finally { setBusy(false); } }}>
    <label className="opportunity-form-full">Apresentação<textarea name="bio" maxLength={3000} defaultValue={profile.bio ?? ""} /></label><label>Anos de experiência<input type="number" min={0} max={80} name="years" defaultValue={profile.experienceYears ?? 0} required /></label><label>Valor por hora<input type="number" min="0.01" max="10000" step="0.01" name="rate" defaultValue={profile.hourlyRate ?? ""} required /></label><label className="opportunity-form-full">Especialidades (separadas por vírgula)<input name="specialties" defaultValue={(profile.specialties ?? []).join(", ")} maxLength={2000} /></label><fieldset className="opportunity-form-full"><legend>Dias disponíveis</legend><div className="weekday-options">{weekdays.map((day, index) => <label key={index}><input type="checkbox" name="day" value={index} defaultChecked={profile.availability?.days?.includes(index)} />{day}</label>)}</div></fieldset><label className="opportunity-form-full">Horários e regiões de atendimento<textarea name="notes" maxLength={1000} defaultValue={profile.availability?.notes ?? ""} /></label><button className="primary" disabled={busy}>Salvar perfil profissional</button>
  </form> : <><p>{profile.city} / {profile.state} · Documentação: {profile.verificationStatus === "approved" ? "Aprovada" : profile.verificationStatus === "under_review" ? "Em análise" : "Ainda não aprovada"}</p><details><summary>O que significa a verificação?</summary><p>Aprovação indica que a documentação cadastrada passou pela análise administrativa. Não garante desempenho, disponibilidade ou adequação a qualquer necessidade de cuidado.</p><p>Converse sobre experiência, tarefas e limites de atuação antes de contratar. Experiência e especialidades são informações do perfil; avaliações de atendimentos são apresentadas separadamente.</p></details><p>{profile.bio || "Apresentação ainda não informada."}</p><p>{profile.experienceYears ?? 0} anos de experiência · {profile.completedContracts} contratos concluídos</p><p>{profile.specialties?.join(" · ")}</p><p>Disponibilidade: {profile.availability?.days?.map(day => weekdays[day]).join(", ") || "A combinar"}. {profile.availability?.notes}</p><p>{profile.rating ? `${profile.rating}/5 (${profile.reviewCount} avaliações)` : "Sem avaliações"}</p></>)}</section>;
}
